/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package universityBlockchainData;


import blockchain.chainserver;
import blockchain.login;
import io.vertx.core.Vertx;


public class App {
    static Vertx vertx = Vertx.vertx();
    public static void main(String[] args) {


        vertx.deployVerticle(new Server());
//        vertx.deployVerticle(new login());
//        System.out.println(new App().getGreeting());
    }
}
