/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package universityBlockchainData;


import blockchain.chainserver;
import blockchain.login;
import io.vertx.core.Vertx;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();

        vertx.deployVerticle(new chainserver());
        vertx.deployVerticle(new login());
//        System.out.println(new App().getGreeting());
    }
}
